services:
  db:
    image: ankane/pgvector
    container_name: pgvector-sms
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: social-media-services
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - social-media-private

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-services
    expose:
      - "8080"
    networks:
      - social-media-private
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db:5432
      POSTGRES_DATABASE: social-media-services
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      RSA_PUBLIC_KEY: /app/keys/app.pub
      RSA_PRIVATE_KEY: /app/keys/app.key
      USERS_API_URL: localhost:8080/api/user_services
    volumes:
      - C:\Users\joaop\OneDrive\Documentos\Velo\keys:/app/keys:ro # ro = Read Only

  nginx:
    image: nginx:alpine
    container_name: sm_nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - social-media-private
      - social-media-services

networks:
  social-media-private:
    internal: true

  social-media-services:
    driver: bridge

volumes:
  pgdata:
    driver: local