services:
  db:
    image: ankane/pgvector
    container_name: sm-pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - social-media-private

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sm-app
    expose:
      - "8080"
    networks:
      - social-media-private
      - microservices
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_CREDENTIALS: /opt/app/credentials.json
      GOOGLE_CLOUD_BUCKET: ${GOOGLE_CLOUD_BUCKET}
      RSA_PUBLIC_KEY: /run/secrets/app.pub
    volumes:
      - type: bind
        source: ${RSA_PUBLIC_KEY}
        target: /run/secrets/app.pub
        read_only: true
      - type: bind
        source: ${GOOGLE_CLOUD_CREDENTIALS}
        target: /opt/app/credentials.json
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: sm-nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - social-media-private
      - social-media-services
      - microservices

networks:
  social-media-private:
    internal: false

  social-media-services:
    driver: bridge

  microservices:
    external: true
volumes:
  pgdata:
    driver: local