services:
  db:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - social-media-private

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-services
    expose:
      - "8080"
    networks:
      - social-media-private
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - social-media-private
      - social-media-services

networks:
  social-media-private:
    internal: true

  social-media-services:
    driver: bridge

volumes:
  pgdata:
