spring:
  application:
    name: SocialMediaServices

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  public:
    key: file:${PBKEY_PATH}
  private:
    key: file:${PVKEY_PATH}

