spring:
  application:
    name: SocialMediaServices

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  public:
    key: file:${RSA_PUBLIC_KEY}
  private:
    key: file:${RSA_PRIVATE_KEY}

